spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bd_smartcity
    username: root
    password: root
    

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
