-- MySQL Script generated by MySQL Workbench
-- Fri May 13 01:46:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_smartcity
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_smartcity` ;

-- -----------------------------------------------------
-- Schema bd_smartcity
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_smartcity` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bd_smartcity` ;

use bd_smartcity;

